### ISSUE TITLE
No Longer Functioning

### ISSUE THREAD

**Issue by NeuroticPixels** [semlar/WorldFlightMap#1]
Not working after today's update. Check curseforge's comments for bugs.

**Comment by Asteaguinity** [comment]
It seems the flight map icon can change in Shadowlands when showing the Bastion teleport network, which is why the ResetTitleAndPortraitIcon function was added to the FlightMapMixin, which naturally only gets added when creating the FlightMapFrame.
The WorldMapFrame is thus missing this function, causing the "attempt to call method 'ResetTitleAndPortraitIcon' (a nil value)" error. The second error seems to be a consequence of the first error.

Simply adding this stub function definition in WorldFlightMap.lua is enough to allow the function call to succeed, seemingly without any negative consequences:

```lua
function WorldMapFrame:ResetTitleAndPortraitIcon()
end
```
